### ISSUE TITLE
两个小建议

### ISSUE THREAD

**Issue by lovaxi** [UjhhgtgTeams/SudokuSolver#4]
1、作者应该加几张截图，让大家看看效果。
2、再发布一个Linux下和Windows下的release可执行包

**Comment by ch3nBo** [comment]
嗯，换成gif效果更好。
第二点无所谓，打包太大了，当然也是可以打包提供一个选择的。

**Comment by FeyXieXzf** [comment]
第二点不做了，截图的话会换成gif的
